# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main_win.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QToolBar,
    QVBoxLayout, QWidget)
import img.picture_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 700)
        icon = QIcon()
        icon.addFile(u":/\u67e5\u8be2/system.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionjfgl = QAction(MainWindow)
        self.actionjfgl.setObjectName(u"actionjfgl")
        self.actionjg = QAction(MainWindow)
        self.actionjg.setObjectName(u"actionjg")
        self.actionu = QAction(MainWindow)
        self.actionu.setObjectName(u"actionu")
        self.actiontjsb = QAction(MainWindow)
        self.actiontjsb.setObjectName(u"actiontjsb")
        self.actionxg = QAction(MainWindow)
        self.actionxg.setObjectName(u"actionxg")
        self.actionsjgl = QAction(MainWindow)
        self.actionsjgl.setObjectName(u"actionsjgl")
        icon1 = QIcon()
        icon1.addFile(u":/\u67e5\u8be2/up.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionsjgl.setIcon(icon1)
        self.actionxjgl = QAction(MainWindow)
        self.actionxjgl.setObjectName(u"actionxjgl")
        icon2 = QIcon()
        icon2.addFile(u":/\u67e5\u8be2/down.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionxjgl.setIcon(icon2)
        self.actionxjgl.setIconText(u"\u4e0b\u7ebf\u4e0b\u67b6\u7ba1\u7406")
        self.actionsjpz = QAction(MainWindow)
        self.actionsjpz.setObjectName(u"actionsjpz")
        self.actionsj = QAction(MainWindow)
        self.actionsj.setObjectName(u"actionsj")
        self.actioncxsb = QAction(MainWindow)
        self.actioncxsb.setObjectName(u"actioncxsb")
        icon3 = QIcon()
        icon3.addFile(u":/\u67e5\u8be2/select.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actioncxsb.setIcon(icon3)
        self.actionpldr = QAction(MainWindow)
        self.actionpldr.setObjectName(u"actionpldr")
        self.action_base = QAction(MainWindow)
        self.action_base.setObjectName(u"action_base")
        self.action_shelf_display = QAction(MainWindow)
        self.action_shelf_display.setObjectName(u"action_shelf_display")
        self.action_top = QAction(MainWindow)
        self.action_top.setObjectName(u"action_top")
        icon4 = QIcon()
        icon4.addFile(u":/\u67e5\u8be2/top.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.action_top.setIcon(icon4)
        self.actionuser_pass = QAction(MainWindow)
        self.actionuser_pass.setObjectName(u"actionuser_pass")
        self.action_report = QAction(MainWindow)
        self.action_report.setObjectName(u"action_report")
        icon5 = QIcon()
        icon5.addFile(u":/\u67e5\u8be2/rep.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.action_report.setIcon(icon5)
        self.actionexport_exl = QAction(MainWindow)
        self.actionexport_exl.setObjectName(u"actionexport_exl")
        self.actionwb = QAction(MainWindow)
        self.actionwb.setObjectName(u"actionwb")
        icon6 = QIcon()
        icon6.addFile(u":/\u67e5\u8be2/warrany.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionwb.setIcon(icon6)
        self.actionprintbx = QAction(MainWindow)
        self.actionprintbx.setObjectName(u"actionprintbx")
        self.action_machine_sw = QAction(MainWindow)
        self.action_machine_sw.setObjectName(u"action_machine_sw")
        icon7 = QIcon()
        icon7.addFile(u":/\u67e5\u8be2/sw.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_machine_sw.setIcon(icon7)
        self.action_warranty_config = QAction(MainWindow)
        self.action_warranty_config.setObjectName(u"action_warranty_config")
        icon8 = QIcon()
        icon8.addFile(u":/\u67e5\u8be2/warrany_conf.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.action_warranty_config.setIcon(icon8)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setPointSize(70)
        self.label.setFont(font)
        self.label.setStyleSheet(u"\n"
"color: rgba(106, 106, 106, 20);")
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 22))
        self.mu_baseinfo = QMenu(self.menubar)
        self.mu_baseinfo.setObjectName(u"mu_baseinfo")
        self.mu_machine = QMenu(self.menubar)
        self.mu_machine.setObjectName(u"mu_machine")
        self.mu_select = QMenu(self.menubar)
        self.mu_select.setObjectName(u"mu_select")
        self.mu_shelf = QMenu(self.menubar)
        self.mu_shelf.setObjectName(u"mu_shelf")
        self.mu_poll = QMenu(self.menubar)
        self.mu_poll.setObjectName(u"mu_poll")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.mu_baseinfo.menuAction())
        self.menubar.addAction(self.mu_machine.menuAction())
        self.menubar.addAction(self.mu_select.menuAction())
        self.menubar.addAction(self.mu_shelf.menuAction())
        self.menubar.addAction(self.mu_poll.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.mu_baseinfo.addAction(self.action_base)
        self.mu_machine.addAction(self.actiontjsb)
        self.mu_machine.addAction(self.actionxg)
        self.mu_machine.addAction(self.actionpldr)
        self.mu_machine.addSeparator()
        self.mu_machine.addAction(self.actionexport_exl)
        self.mu_machine.addSeparator()
        self.mu_machine.addAction(self.action_warranty_config)
        self.mu_machine.addAction(self.actionprintbx)
        self.mu_select.addAction(self.actioncxsb)
        self.mu_select.addSeparator()
        self.mu_select.addAction(self.action_top)
        self.mu_select.addSeparator()
        self.mu_select.addAction(self.action_report)
        self.mu_select.addSeparator()
        self.mu_select.addAction(self.actionwb)
        self.mu_shelf.addAction(self.actionsjgl)
        self.mu_shelf.addAction(self.actionxjgl)
        self.mu_shelf.addAction(self.action_machine_sw)
        self.mu_shelf.addSeparator()
        self.mu_shelf.addAction(self.action_shelf_display)
        self.mu_poll.addAction(self.actionsjpz)
        self.mu_poll.addAction(self.actionsj)
        self.menu.addAction(self.actionuser_pass)
        self.toolBar.addAction(self.actioncxsb)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsjgl)
        self.toolBar.addAction(self.actionxjgl)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_top)
        self.toolBar.addAction(self.action_machine_sw)
        self.toolBar.addAction(self.action_report)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_warranty_config)
        self.toolBar.addAction(self.actionwb)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u673a\u623f\u8bbe\u5907\u7ba1\u7406\u7cfb\u7edfpyside6-V1.0", None))
        self.actionjfgl.setText(QCoreApplication.translate("MainWindow", u"\u673a\u623f\u7ba1\u7406", None))
        self.actionjg.setText(QCoreApplication.translate("MainWindow", u"\u673a\u67dc\u7ba1\u7406", None))
        self.actionu.setText(QCoreApplication.translate("MainWindow", u"U\u4f4d\u7ba1\u7406", None))
        self.actiontjsb.setText(QCoreApplication.translate("MainWindow", u"\u8865\u5f55\u8bbe\u5907", None))
#if QT_CONFIG(tooltip)
        self.actiontjsb.setToolTip(QCoreApplication.translate("MainWindow", u"\u8865\u5f55\u8bbe\u5907", None))
#endif // QT_CONFIG(tooltip)
        self.actionxg.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u8bbe\u5907\u4fe1\u606f", None))
        self.actionsjgl.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4e0a\u67b6\u7ba1\u7406", None))
#if QT_CONFIG(tooltip)
        self.actionsjgl.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4e0a\u67b6", None))
#endif // QT_CONFIG(tooltip)
        self.actionxjgl.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u7ebf\u4e0b\u67b6\u7ba1\u7406", None))
#if QT_CONFIG(tooltip)
        self.actionxjgl.setToolTip(QCoreApplication.translate("MainWindow", u"\u4e0b\u7ebf\u4e0b\u67b6\u7ba1\u7406", None))
#endif // QT_CONFIG(tooltip)
        self.actionsjpz.setText(QCoreApplication.translate("MainWindow", u"\u5de1\u68c0\u914d\u7f6e", None))
        self.actionsj.setText(QCoreApplication.translate("MainWindow", u"\u5de1\u68c0\u64cd\u4f5c", None))
        self.actioncxsb.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2\u8bbe\u5907", None))
        self.actionpldr.setText(QCoreApplication.translate("MainWindow", u"\u6279\u91cf\u5bfc\u5165\u8bbe\u5907", None))
        self.action_base.setText(QCoreApplication.translate("MainWindow", u"\u57fa\u7840\u4fe1\u606f\u7ba1\u7406", None))
        self.action_shelf_display.setText(QCoreApplication.translate("MainWindow", u"\u4e0a\u4e0b\u67b6\u4fe1\u606f\u67e5\u8be2", None))
        self.action_top.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u843d\u4f4d\u56fe", None))
        self.actionuser_pass.setText(QCoreApplication.translate("MainWindow", u"\u7528\u6237\u767b\u5f55\u5bc6\u7801", None))
        self.action_report.setText(QCoreApplication.translate("MainWindow", u"\u7edf\u8ba1\u5206\u6790", None))
        self.actionexport_exl.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u8bbe\u5907\u4fe1\u606f", None))
        self.actionwb.setText(QCoreApplication.translate("MainWindow", u"\u7ef4\u4fdd\u4fe1\u606f\u67e5\u8be2", None))
        self.actionprintbx.setText(QCoreApplication.translate("MainWindow", u"\u6807\u7b7e\u7ba1\u7406", None))
        self.action_machine_sw.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4f4d\u7f6e\u8c03\u6574", None))
        self.action_warranty_config.setText(QCoreApplication.translate("MainWindow", u"\u7ef4\u4fe1\u606f\u914d\u7f6e", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f\u7ba1\u7406\u7cfb\u7edf\n"
" PySide6-V1.0", None))
        self.mu_baseinfo.setTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u7840\u4fe1\u606f", None))
        self.mu_machine.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u7ba1\u7406", None))
        self.mu_select.setTitle(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2\u7ba1\u7406", None))
        self.mu_shelf.setTitle(QCoreApplication.translate("MainWindow", u"\u4e0a\u4e0b\u67b6\u7ba1\u7406", None))
        self.mu_poll.setTitle(QCoreApplication.translate("MainWindow", u"\u5de1\u68c0\u7ba1\u7406", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u5e38\u7528\u767b\u5f55\u4fe1\u606f", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

